# Generated by Django 5.1.3 on 2024-11-20 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='fabricante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='sistema_operativo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='tipo',
            field=models.CharField(choices=[('PC', 'PC'), ('Móvil', 'Móvil'), ('Otro', 'Otro')], default='Otro', max_length=20),
        ),
    ]
